### ISSUE TITLE
[FEATURE REQUEST] Windows SDK 11 24H2

### ISSUE THREAD

**Issue by chadlwilson** [noseratio/choco#29]
Are these packages still vaguely maintained? :-)

Would be nice to get the latest Windows SDK (`10.0.26100` / `24H2` at time of writing) as a Chocolatey package: https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/

https://download.microsoft.com/download/2/6/f/26f7aa55-ef6f-4882-b19b-a1be0e7328fe/KIT_BUNDLE_WINDOWSSDK_MEDIACREATION/winsdksetup.exe

Would you accept a PR and be interested in shepherding it through?

**Comment by noseratio** [comment]
I myself moved to use Winget: 

‘winget install -e --id Microsoft.WindowsSDK’

Basically, since then I stopped updating this passage.TBH, I didn't suspect some other people were using it, sorry about that. Is there any reason you can't use Winget, too?

**Comment by chadlwilson** [comment]
Probably not, other than not being familiar with it, and using chocolatey for other stuff, to be honest. But that's a reasonable suggestion if it supports the same level of automated install so will give it a go.

**Comment by chadlwilson** [comment]
After a bit of digging, the problem is that winget is not really supported/stable on Windows Server 2022. I use chocolatey to configure windows server 2022 core container images in docker builds, and need something stable to install dependencies for use at build time by automation. But yeah, no big deal, will just keep using the old Windows SDK chocolatey package for now.
