### ISSUE TITLE
wsudo doesn't work properly in cmder(?)

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [noseratio/choco#4]
If you run wsudo in cmder, it opens up a new powershell window instead of running the command in the existing one.

**Comment by noseratio** [comment]
@no-boot-device, I'm not using `cmder`, but wouldn't it be the same problem with the plain `cmd.exe`? If `cmd` is running non-elevated, then `Start-Process -Wait -Verb runAs...` will create a separate elevated admin console anyway. Could you try this in `cmder`:

    powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Process -Wait -Verb RunAs -FilePath cmd -ArgumentList '/c echo Elevated! & pause'"

I expect it to create a new console, is this not the case?
Other than that, if you already run either `cmd` or `cmder` in elevated mode, you won't need `wsudo` at all.
