### ISSUE TITLE
[wsudo] Feature request; Prevent new Shell/Instance/Window

### ISSUE THREAD

**Issue by AndBroCorp** [noseratio/choco#5]
Prevent opening of new shells on use especially when you just run `wsudo` command in a shell.
Alternatively create a `wsu` that keep the current shell.

**Comment by noseratio** [comment]
Thanks @AndBroPLAYipp, it's a great suggestion, I'll get to it.

**Comment by noseratio** [comment]
Hey @AndBroPLAYipp, I've finally got to chance to attend to this. A few points:

- If you start `wsudo`/`wasudo` from a non-elevated shell, there still will be a separate window. That's just how elevation works in Windows, we can't explicitly attach an admin console to an existing non-admin console. There're some smart redirection techniques out there to solve this but this is beyond the purpose of `wsudo` as I see it. Check out [`gsudo`](https://github.com/gerardog/gsudo) by @gerardog for a great alternative.

- If *already* in an elevate console, I can make this work for `wsudo` and `wsudox`, they would essentially map to `cmd /c <command>`. 
However, I'd like leave `wasudo` and `wasudox` to behave the same way they currently do, that is to open a new console async console and run the `<command>` there, while returning to the caller immediately. That'd be consistent with their asynchronous semantic.

Would you have any comment on that?
