### ISSUE TITLE
Add alias "sudo" for "wsudo"

### ISSUE THREAD

**Issue by Masken8** [noseratio/choco#6]

**Comment by Neurognostic** [comment]
Shouldn't that be the responsibility of the user? Just add it to your `$PROFILE`.

```powershell
Add-Content $PROFILE "`r`nSet-Alias sudo wsudo`r`n"
```

**Comment by noseratio** [comment]
Actually I agree, because there're other Windows `sudo` implementations out there that can be run side-by-side, so it's better to leave it up the the user to create an alias.
